### ISSUE TITLE
Successor check macro

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#101]
From @ueliwechsler's comment [here](https://github.com/JuliaReach/MathematicalSystems.jl/pull/99#discussion_r352278330):

> I have written a quick macro as a first draft (see below). I am not really used to metaprogramming, so if you have any inputs on how I could improve this or where I have to be careful, this would be great. But I guess, we can discuss this in a new issue.

```julia
using MathematicalSystems, LazySets, BenchmarkTools

@inline _is_conformable_state(system, x) = statedim(system) == length(x)
@inline _is_conformable_input(system, u) = inputdim(system) == length(u)
@inline _in_stateset(system, x) = x ∈ stateset(system)
@inline _in_inputset(system, u) = u ∈ inputset(system)

function successor(system::LinearDiscreteSystem, x::AbstractVector; check=true)
    check && !_is_conformable_state(system, x) && throw(ArgumentError("invalid arguments"))
    return system.A * x
end

function successor(system::ConstrainedLinearControlDiscreteSystem, x::AbstractVector, u::AbstractVector; check=true)
    check && (!_is_conformable_state(system, x) || !_is_conformable_input(system, u) || !_in_stateset(system, x) || !_in_inputset(system, u)) && throw(ArgumentError("invalid arguments"))
    return system.A * x + system.B * u
end

macro comformable(expr)
    func = expr.args[1]
    kw1 = Expr(:kw, :check, false)
    vals = []
    for vl in expr.args[2:end]
        if !(typeof(vl) <: Expr)
            push!(vals, vl)
        end
    end
    func2 = Expr(:call, func, vals..., kw1 )
    return esc(func2)
end

A = [1. 1; 1 -1]
B = Matrix([0.5 1.5]')
X = Hyperrectangle([0.0, 0.3], [2.0, 2.0])
U = Interval(0.0, 1.0)
sys = ConstrainedLinearControlDiscreteSystem(A, B, X, U)
x = [0.0; 0.3]
u = [0.5]

x1 = @btime successor($sys, $x, $u; check=true)
#  198.276 ns (3 allocations: 288 bytes)
x2 = @btime @comformable successor($sys, $x, $u)
# 187.421 ns (3 allocations: 288 bytes)
```

And the corresponding error messages:
```julia
x = [0.0; 0.3; 0.3] # has wrong dimensions
u = [0.5]
x1 = successor(sys, x, u; check=true)
# ERROR: ArgumentError: invalid arguments
x2 = @comformable successor(sys, x, u)
# ERROR: DimensionMismatch("second dimension of A, 2, does not match length of x, 3")
```

_Originally posted by @ueliwechsler in https://github.com/JuliaReach/MathematicalSystems.jl/pull/99_

**Comment by ueliwechsler** [comment]
Is there still a need for this, let's call it, `@avoid_checks` macro since there is only one keyword left?
Would this improve usability?

**Comment by schillic** [comment]
It should be a short command, like `@nochecks`, but that name is not really appropriate anymore because some checks are still performed. The name would be more justifiable if there were more cases where it applies.

The main benefits of such a macro are that
1. you can write it around a function call instead of having to add this keyword multiple times, and
2. you can do this from the outside (i.e., as a user).

So yes, the macro has a use case. But I do not consider it important. Still, I would not close the issue. It is a good exercise with macros at least :wink:

**Comment by mforets** [comment]
> Is there still a need for this, let's call it, @avoid_checks macro since there is only one keyword left?
Would this improve usability?

I don't consider having that macro improves usability. The kwarg is fine. I would close the issue.
