### ISSUE TITLE
Add discretize methods for AbstractContinous system

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/MathematicalSystems.jl#107]
I was playing around with the idea of adding a method that discretizes an `AbstractContinuousSystem` by using either the exact discretization or an Euler discretization if `rank(A) != size(A,1)`, i.e. `A` not invertible.

The method signature would look like this:
`discretize(sys::AbstractContinuousSystem, ΔT::Real)::AbsttractDiscreteSystem`

**Comment by mforets** [comment]
For the case of continuous ODEs with initial *sets*, we have discretization methods in [this file](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/discretize.jl). On the other hand, i'm not opposed to having discretization methods with finite differences etc into this library. Do you have a use case in mind?

Methods like linearization would also be useful. But should also watch for existing Julia libraries and try to re-use if possible.

**Comment by mforets** [comment]
> using either the exact discretization

What do you mean by exact discretization? For which class of systems?

**Comment by ueliwechsler** [comment]
> What do you mean by exact discretization? For which class of systems?

I am talking only about all linear and affine systems implemented in `MathematicalSystems` such as e.g. `x' = A*x + B*u`.

The algorithms so far are nothing sophisticated. Either a Euler Discretization:
```julia
A_d = (I + ΔT*A),       B_d = ΔT*B
```
or the exact solution for the discretization of a linear system
```julia
A_d = exp(A*ΔT),       B_d = inv(A)*(A_d - I)*B
```

> Do you have a use case in mind?

The use case is MPC where we often need a discretization for a given continuous linear system. I would consider this a convenience function used like this:
`dsys = discretise(@system x' = A*x + B*u, ΔT)`

Or do you mean, why I suggest having the discretization in `MathematicalSystems` and not in a "higher level" package?


Another use case is the discretization of a non-linear system in MPC. Where first the  linearization and then a discretization of a given continuous non-linear system would be done (this is also why I thinking about how and where to add linearization functionalities)

**Comment by mforets** [comment]
Ok, i see.

I agree to add a discretization function to this library, i think it is a good idea.

**Comment by ueliwechsler** [comment]
Do you suggest adding other approaches than the ones described above?

**Comment by ueliwechsler** [comment]
I have a first working version of the discretize function in the branch `discretize` in my fork:

https://github.com/ueliwechsler/MathematicalSystems.jl/blob/9b81f45e1a96e0a9e5bb97ab0e80076643c2c48a/src/discretize.jl#L55-L123

I will add docstrings as soon as I have time. Comments are welcome 😉

**Comment by schillic** [comment]
> I have a first working version of the discretize function in the branch discretize in my fork

* I would not redefine the algorithm [here](https://github.com/ueliwechsler/MathematicalSystems.jl/blob/9b81f45e1a96e0a9e5bb97ab0e80076643c2c48a/src/discretize.jl#L59-L63). If I pass `algo=:exact`, then I would rather expect an error. For a convenient default algorithm I would set `algo=:default` which finds out the algorithm for you:

```julia
    if algo == :default
        if rank(sys.A) == size(sys.A, 1)
            # A is invertible, use exact discretizaion
            algo = :exact
        else
            # A is not invertible, use approximate discretizaion
            algo = :euler
        end
    end
```

* I would also rename the keyword argument to `algorithm`.

* [Here](https://github.com/ueliwechsler/MathematicalSystems.jl/blob/9b81f45e1a96e0a9e5bb97ab0e80076643c2c48a/src/discretize.jl#L74-L84) I would add an `else` case printing an error message that the algorithm is not known.

* Currently there are multiple methods with the name `discretize`, which are all exported. If I understand correctly, only the first one should be used from the outside. If that is the case, maybe rename the other methods.

* Consider using sparse matrices/vectors instead of the `zeros`.

* The `_corresponding_type` function seems useful and can be defined together with the system definitions (by slightly changing the constructors)

https://github.com/JuliaReach/MathematicalSystems.jl/blob/959cbbb888e8e309f776b2c8d46a0ddc7b62ca60/src/systems.jl#L9-L10

to (not tested)

```julia
defs = ((:ContinuousIdentitySystem, :AbstractContinuousSystem),
        (:DiscreteIdentitySystem, :AbstractDiscreteSystem))
for (Z, AZ) in defs
    ...
end
@eval begin
    _corresponding_type(::$(defs[1][1])) = $(defs[2][1])
end
```

**Comment by ueliwechsler** [comment]
Thanks a lot for your review!
I have implemented the first three and the second last points directly in the code.

> * Currently there are multiple methods with the name `discretize`, which are all exported. If I understand correctly, only the first one should be used from the outside. If that is the case, maybe rename the other methods.

You are right. I am also not sure if the implementation with all the different `discretize` methods which dispatch all on the `discretize(A::AbstractMatrix, B::AbstractMatrix, c::AbstractVector, D::AbstractMatrix, ΔT::Real; algorithm=:exact)` method is the best (or a reasonable) thing to do.

> * The `_corresponding_type` function seems useful and can be defined together with the system definitions (by slightly changing the constructors)

Indeed, I also use it for the `@system` macro, but there with the signature `_corresponding_type(abstract_type, fields::Tuple)` which will be used as `_corresponding_type(AbstractDiscreteSystem, (:A,:B))` which I think cannot be added within the system definition. But I could still add the basic definition in the system definition as
```julia
@eval begin
_corresponding_type(::$(defs[1][1])) =  $(defs[2][1])
_corresponding_type(::Type($(defs[1][1]))) =  $(defs[2][1])
end
```
where the  second method allows to call it as `_corresponding_type(LinearDiscreteSystem)` and the first method as `_corresponding_type(LinearDiscreteSystem(rand(2,2)))`

The question is, if it is worth to have that additional effort and add it in all system definitions or if the version I implemented is sufficient? 
```julia
function _corresponding_type(sys::AbstractSystem)
    sys_type = (typeof(sys))
    return _corresponding_type(sys_type)
end

function _corresponding_type(sys_type::Type{<:AbstractSystem})
    fields = fieldnames(sys_type)
    return _corresponding_type(supertype(sys_type), fields)
end

function _corresponding_type(abstract_type, fields::Tuple)
      @show abstract_type, fields
    TYPES = subtypes(abstract_type)
    TYPES_FIELDS = fieldnames.(TYPES)
    is_in(x, y) = all([el ∈ y for el in x])
    idx = findall(x -> is_in(x, fields) && is_in(fields,x), TYPES_FIELDS)
    if length(idx) == 0
        error("$(fields) does not match any system type of MathematicalSystems")
    end
    return TYPES[idx][1]
end
```

**Comment by ueliwechsler** [comment]
As an alternative for `_corresponding_type` here is a faster version.
```julia
function _corresponding_type(sys)
    sys_type = Base.typename(typeof(sys))
    type_string = string(sys_type)
    if supertype(typeof(sys)) == AbstractDiscreteSystem
        type_string =  replace(type_string, "Discrete" => "Continuous")
    else
        type_string =  replace(type_string, "Continuous" => "Discrete")
    end
    return eval(Meta.parse(type_string))
end
```

**Comment by schillic** [comment]
> here is a faster version

I doubt that it is faster in execution.
And it relies on a naming convention that might not be true in user code.
But it is a reasonable thing to do, so I am fine with it.

**Comment by ueliwechsler** [comment]
in my quick benchmark it was significantly faster but not as robust as the other one.
```
julia> @time _corresponding_type(sys)
(abstract_type, fields) = (AbstractContinuousSystem, (:A,))
  0.021586 seconds (4.79 k allocations: 1.121 MiB)
LinearContinuousSystem

julia> @time _corresponding_type_new(sys)
  0.000063 seconds (58 allocations: 2.828 KiB)
LinearContinuousSystem
```

**Comment by schillic** [comment]
Ah, with `_corresponding_type` being the implementation [here](https://github.com/JuliaReach/MathematicalSystems.jl/issues/107#issuecomment-566585268) - this I can believe. I thought compared to the explicit definition `_corresponding_type(::Type{<:LinearDiscreteSystem}) = LinearContinuousSystem)` etc.

**Comment by ueliwechsler** [comment]
> And it relies on a naming convention that might not be true in user code.
> But it is a reasonable thing to do, so I am fine with it.

And it is also a lot less effort to implement than the explicit definition.
