### ISSUE TITLE
Map fails if A is a variable

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#113]
```julia
julia> @map x -> rand(2, 2) * x  # ok
MathematicalSystems.LinearMap{Float64,Array{Float64,2}}([0.8889919743522887 0.1607072511950136; 0.5439088199011097 0.5514228069532758])

julia> A = rand(2, 2);

julia> @map x -> A*x # fails
UndefVarError: A not defined

Stacktrace:
 [1] top-level scope
 [2] eval at ./boot.jl:330 [inlined]
 [3] eval(::Symbol) at /home/mforets/.julia/dev/MathematicalSystems/src/MathematicalSystems.jl:2
 [4] top-level scope at /home/mforets/.julia/dev/MathematicalSystems/src/macros.jl:81
 [5] top-level scope at In[36]:2
```

**Comment by ueliwechsler** [comment]
I think the problem is, that the variable `A` is not defined in the Namespace of the Macro, i.e. there is no `MathematicalSystems.A` variable available. 

See this nonsensical MVP:
```julia
module Test
    LinearMap(x) = x
    D = 1
    macro map(expr)
        return eval(quote Expr(:call, :LinearMap, :D)end)
    end
    macro map_main(expr)
        return eval(quote Expr(:call, :LinearMap, :(Main.:D))end)
    end
end
Test.@map x -> B*x #works (D in Test.D is used)
Test.@map_main x -> B*x #fails, D not defined
D = rand(2,2)
Test.@map_main x -> B*x #works Main.D is used
```
So one solution would be to add the correspondig variable to `:(Main.D)` in the Macro.

**Comment by ueliwechsler** [comment]
I have to add that according to this post [SO](https://stackoverflow.com/questions/42299444/scope-of-expressions-and-variables-in-julia-macro-in-modules) `eval` should not be used in macros. The scoping issue can be solved using `esc`.
E.g.
```julia
module Test
    LinearMap(x) = x
    macro map_right(expr)
        return Expr(:call, :LinearMap, esc(:E))
    end
end
Test.@map_right x -> B*x # fails: UndefVarError: E not defined
E = rand(2,2)
Test.@map_right x -> B*x # passes
```

**Comment by mforets** [comment]
Thanks for looking into this! I couldn't use idea to make the the map macro work yet. The line that fails is

https://github.com/JuliaReach/MathematicalSystems.jl/blob/40d49de39bfc47aadd4c1b297b6409d034c7a4a1/src/macros.jl#L81

where `MT` is in this case a `LinearMap` (in the same scope as the macro so that is ok), and `matched[_A]` contains the symbol `:A` which should be evaluated in the scope of the calling site. I tried `MT(esc(matched[:_A]))` and `Expr(:call, MT, esc(matched[:_A]))` but none of them works..

**Comment by blegat** [comment]
You probably need to use `esc`

**Comment by ueliwechsler** [comment]
I finally have a solution... I think.
But somehow I am still not sure what happens for real.
so you can do `return esc(:(LinearMap($(matched[:_A]))))` and then it should work
consider the branch https://github.com/ueliwechsler/MathematicalSystems.jl/tree/macro_map in my fork for the implementation

**Comment by mforets** [comment]
Very good, you nailed it :+1: 
Do you mind of making a PR, or should i do it?

One little problem is that the macro looks for the `LinearMap` type defined in the calling scope. Ideally it should only use `MathematicalSystems.LinearMap`. For instance, if you do

```julia
using LazySets, MathematicalSystems

@map x -> [1 0; 0 0]*x

WARNING: both LazySets and MathematicalSystems export "LinearMap"; uses of it in module Main must be qualified
UndefVarError: LinearMap not defined
```
One workaround is to return `esc(:(MathematicalSystems.LinearMap($(matched[:_A]))))`.

**Comment by ueliwechsler** [comment]
I found out, how it is supposed to be 😁
`Expr(:call,:($MT),esc(:($(matched[:_A]))))`

I can do the PR. Do you need any additional tests or docstrings?

**Comment by mforets** [comment]
Cool. Let's add a test that failed [in the OP](https://github.com/JuliaReach/MathematicalSystems.jl/issues/113#issue-536648957), either in the as a `jldoctest` in the macro docstring or (better) as a new test in `test/maps.jl`.

**Comment by mforets** [comment]
or `test/macros.jl` it doesn't matter.

**Comment by mforets** [comment]
@JuliaRegistrator register()
