### ISSUE TITLE
Add Equality operator 

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/MathematicalSystems.jl#119]
To utilize some unit tests, I defined an equality operator for a struct `sys::AbstractSystem` as
```julia

import Base.==
import Base.≈

export _corresponding_type, discretize

function ==(sys1::AbstractSystem, sys2::AbstractSystem)
    if typeof(sys1)!== typeof(sys2)
        return false
    end
    for field in fieldnames(typeof(sys1))
        if getfield(sys1, field) != getfield(sys2, field)
            return false
        end
    end
    return true
end

function ≈(sys1::AbstractSystem, sys2::AbstractSystem)
    if typeof(sys1)!== typeof(sys2)
        return false
    end
    for field in fieldnames(typeof(sys1))
        if !(getfield(sys1, field) ≈ getfield(sys2, field))
            return false
        end
    end
    return true
end
```

What is your opinion on adding the `==` and ` ≈` operator to the package?

**Comment by mforets** [comment]
+1 i agree to overload those operators in the way you propose. One question though: does it work if the struct is composed, e.g. an `InitialValueProblem`? Or we need to call it recursively?

**Comment by blegat** [comment]
This won't allow using keyword with `isapprox`, I would overload `Base.isapprox` instead of `≈`.

**Comment by mforets** [comment]
Ok, and then for the comparison we can pass `isapprox(getfield(sys1, field), getfield(sys2, field); kwargs...)`. ([The operator `≈` falls back to `isapprox`](https://github.com/JuliaLang/julia/blob/46ce4d79337bdd257ee2e3d2f4bb1c55ff0a5030/base/floatfuncs.jl#L277)).

**Comment by ueliwechsler** [comment]
> does it work if the struct is composed, e.g. an InitialValueProblem? Or we need to call it recursively??

It should work since `InitialValueProblem` is also of type `AbstractSystem`.

**Comment by mforets** [comment]
Yes, I was wondering if something extra needs to be added, but it is not the case as the initial value problems' field `s` is itself a system, so `getfield(sys1, field) != getfield(sys2, field)` calls again the new `==` when the considered field is `:s`. For the initial set, it will use whatever equality is defined for the given type of initial set.
