### ISSUE TITLE
Add getter functions for field names

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#126]
_Originally posted by @ueliwechsler in https://github.com/JuliaReach/MathematicalSystems.jl/pull/124#issuecomment-568711999_

**Comment by ueliwechsler** [comment]
Considering the field names for affine systems, an idea would be:
`state_matrix` for `A`
`input_matrix` for `B`
`noise_matrix ` for `D`
`affine_term` for `c`
