### ISSUE TITLE
Parse scalar affine continuous system

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#140]
Similar to `@system(x' = 2x)`, i think we should be able to parse:

```julia
julia> @system(x' = 2x + 1)
ERROR: MethodError: no method matching AffineContinuousSystem(::Int64, ::Int64)
Stacktrace:
 [1] top-level scope at REPL[9]:1
```

**Comment by ueliwechsler** [comment]
Same goes for `@system(x⁺ = 0.5x + u)`
```julia
MethodError: no method matching LinearControlDiscreteSystem(::Float64, ::IdentityMultiple{Float64})
Closest candidates are:
  LinearControlDiscreteSystem(!Matched::MTA, ::MTB) where {T, MTA<:AbstractArray{T,2}, MTB<:AbstractArray{T,2}} at C:\Users\wueli\.julia\dev\MathematicalSystems\src\systems.jl:222
in top-level scope at ifmpc.jl:10
```

**Comment by ueliwechsler** [comment]
I am not sure how to handle `@system(x⁺ = 0.5x + u)`  
```julia
MethodError: no method matching LinearControlDiscreteSystem(::Float64, ::IdentityMultiple{Float64})
```
Either we need to convert the `Float64` argument to a `Matrix{Float64}` or the `IdentityMultiple` to a scalar (or change the signature of the constructors). 
The `@system` macro needs to check if the dimension of `A=0.5` is `1` (then we  need `B=1`) or bigger than `1` (then we need `B=MultipleIdentity(state_dim)`).
So far, I couldn't make the dynamic dimension check work within the macro.

**Comment by schillic** [comment]
> Either we need to convert the Float64 argument to a Matrix{Float64} or the IdentityMultiple to a scalar (or change the signature of the constructors).

I think the behavior should be consistent with `@system(x⁺ = x)` and `@system(x⁺ = x + u)`.

**Comment by ueliwechsler** [comment]
That means it should create a ` LinearControlDiscreteSystem(::Float64, ::Float64)`.

**Comment by schillic** [comment]
Or we change the behavior of the other cases. Either way is fine with me but other people may have an opinion.

**Comment by ueliwechsler** [comment]
I did some thinking 😅
A proposal would be to convert every input into a `matrix` or `vector` see #175 as a possible solution.
