### ISSUE TITLE
Getter function for initial state in IVP

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#144]
Proposal: add a new getter function for the `x0` field (initial state) in an initial-value problem. Possible name: `initial_state`, or `initstate`.

**Comment by schillic** [comment]
Maybe `initial_state` and shorter aliases `init` and `x0`?

**Comment by ueliwechsler** [comment]
`initial_state` looks the clearest, but `initialstate` would be more in line with the other getter functions `stateset`, `statedim` ...

**Comment by mforets** [comment]
Thanks for your inputs. Let's use `initial_state` then. I think we agree that `initialstate` seems too compressed. Tab completion helps to figure out the correct method, in any case.
