### ISSUE TITLE
Handle @system(x' = Ax + Bw)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#163]
```julia
julia> @system(x' = Ax + Bw)
ArgumentError: the entry (:A, :D) does not match a `MathematicalSystems.jl` structure

Stacktrace:
 [1] top-level scope at In[14]:1
```

This should give a better error mesage, or create a linear continuous system, or create a noisy system without constrints (but this https://github.com/JuliaReach/MathematicalSystems.jl/issues/162).

**Comment by ueliwechsler** [comment]
Should we add a new issue for a better error message?
