### ISSUE TITLE
Clean up doc of system types

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/MathematicalSystems.jl#177]
The doc for the systems types is not consistent.

In some cases, there is a `for all k`  for `discrete` systems and for affine systems there is an additional `and c a vector` in some cases.

We should clean this up. I think removing this would be best.

**Comment by schillic** [comment]
Something like this?

https://github.com/JuliaReach/MathematicalSystems.jl/blob/54c301392aefbd85c3f4d12a3bef7ce3c0ffe0ca/src/systems.jl#L429-L432

I would rather keep it.

**Comment by ueliwechsler** [comment]
Okay. I can add `\\text{ for all } k` and `\\text{ for all } t ` for every type.

What about the phrasing "with state constraints" which is used for `noisy` and `controlled` systems as well? Because the systems often have input constraints and bound on the noise as well.

**Comment by schillic** [comment]
> What about the phrasing "with state constraints" which is used for `noisy` and `controlled` systems as well? Even though these systems also have input constraints and a bound on the noise as well.

Maybe we can just say "with domain constraints." Otherwise I do not see a good formulation except spelling it out as in "with constraints on the state, input, and noise domains."

**Comment by ueliwechsler** [comment]
> Okay. I can add `\\text{ for all } k` and `\\text{ for all } t ` for every type.

Would "For all t" and "for all k" not be inexact since normally `k>=0` and `t>=0` as well?
​

**Comment by schillic** [comment]
> Would "For all t" and "for all k" not be inexact since normally `k>=0` and `t>=0` as well?

Yes, but from context it should be clear that there is no negative iteration/time point.
