### ISSUE TITLE
LTI systems type

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#18]
In control books, (continuous) LTI systems are those of the form: `x' = Ax + Bu; y = Cx + Du`.

Proposal: define a `LinearTimeInvariantContinuousSystem` with fields `A, B, C, D` and another one `ConstrainedLinearTimeInvariantContinuousSystem` with fields `A, B, C, D, X, U`.

**Comment by blegat** [comment]
Shouldn't we do composition here to add output to a system like
```julia
abstract type AbstractMap end
struct LinearMap{MT<:AbstractMatrix}
    A::MT
end
struct LinearControlMap{MT<:AbstractMatrix}
    A::MT
    B::MT
end
struct SystemWithOutput{ST<:AbstractSystem, MT<:AbstractMap}
    system::ST
    outputmap::MT
end
```
the name `SystemWithOutput` isn't nice though.

**Comment by mforets** [comment]
`SystemWithOutput` is correct. Alternatives i can think of are `OutputSystem`, `MappedSystem`, but i'm not really convinced.

**Comment by nikos-kekatos** [comment]
there is the HIOA (hybrid input output automata)

**Comment by mforets** [comment]
i'm considering to add the output as an extension field as in a `HybridSystem`, like:

```julia
struct ConstrainedLinearControlContinuousSystem{T, MT <: AbstractMatrix{T}, ST, UT} <: AbstractContinuousSystem
    A::MT
    B::MT
    X::ST
    U::UT
    # Can be used by extensions
    ext::Dict{Symbol, Any}
end

function ConstrainedLinearControlContinuousSystem{T, MT <: AbstractMatrix{T}, ST, UT}(A::MT, B::MT, X::ST, U::UT)
    @assert Base.LinAlg.checksquare(A) == size(B, 1)
    return ConstrainedLinearControlContinuousSystem{T, MT, ST, UT}(A, B, X, U, Dict{Symbol, Any}())
end

function ConstrainedLinearControlContinuousSystem{T, MT <: AbstractMatrix{T}, ST, UT}(A::MT, B::MT, X::ST, U::UT, ext::Dict{Symbol, Any})
    @assert Base.LinAlg.checksquare(A) == size(B, 1)
    return ConstrainedLinearControlContinuousSystem{T, MT, ST, UT}(A, B, X, U, ext)
end
```

such that `ext` could be `ext = Dict(:output=>LinearControlMap(A, B))`.

i don't know if there are reason to prefer one design over the other.

**Comment by blegat** [comment]
The disadvantage of the `ext` field is that it won't be able to know that there are output using only type information
