### ISSUE TITLE
Packages using MathematicalSystems.jl

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#231]
i thought we had a list of packages using this one, but it seems there isn't.

---

- https://github.com/JuliaReach/ReachabilityAnalysis.jl
- https://github.com/ONSAS/StructuralDynamicsODESolvers.jl

**Comment by blegat** [comment]
A few others:
* https://github.com/dionysos-dev/Dionysos.jl
* https://github.com/blegat/SwitchOnSafety.jl
* https://github.com/blegat/HybridSystems.jl
* https://github.com/JuliaReach/SpaceExParser.jl

**Comment by mforets** [comment]
Awesome @blegat  ! I'll add a note with this somewhere in the docs.
