### ISSUE TITLE
Type piracy on `I`

### ISSUE THREAD

**Issue by baggepinnen** [JuliaReach/MathematicalSystems.jl#246]
This line
https://github.com/JuliaReach/MathematicalSystems.jl/blob/8722f9be6130ebcfdf2e0e0b50876f1483563f40/src/identity.jl#L170
breaks all code that uses `LinearAlgebra.I`.
The default value for the `N` argument means that a method is defined for `LinearAlgebra.I(n::Int)` which overwrites the default `LinearAlgebra.I(::Int)`, any code that expects 
```julia
julia> I(2)
2×2 Diagonal{Bool, Vector{Bool}}:
 1  ⋅
 ⋅  1
```
will now get an 
```julia
julia> I(2)
MathematicalSystems.IdentityMultiple{Float64} of value 1.0 and order 2
```
and most likely error. The solution for this is to avoid type piracy by choosing another name (not `I`) for your identity, or to use the name `I` but not import and extend `LinearAlgebra.I`.

See also https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/649

**Comment by mforets** [comment]
Fixed by https://github.com/JuliaReach/MathematicalSystems.jl/pull/248
