### ISSUE TITLE
Euler discretization may be wrong 

### ISSUE THREAD

**Issue by baggepinnen** [JuliaReach/MathematicalSystems.jl#250]
https://github.com/JuliaReach/MathematicalSystems.jl/blob/04bd7cc7043f9ee623ee4a2088af393ec3154145/src/discretize.jl#L192

I'm pretty sure you shouldn't change the D matrix, and likely only multiply either C or B by dt.

**Comment by blegat** [comment]
`D` is not the matrix linking the input `u` to the output `y` as it is usual for LTI system. Here, it is the matrix linking the disturbance `w` to the state `x`. Because it affects the state `x`, you multiply if by `ΔT`.

**Comment by baggepinnen** [comment]
Ah my bad, I was just browsing through the code to see what the package was about and mas missing some relevant context, sorry for the noise!

**Comment by blegat** [comment]
No worry, thanks for proofreading the code!
