### ISSUE TITLE
Bikeshedding exports

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#38]
In MathematicalSystems all types are exported,

```julia
export ContinuousIdentitySystem,
       ConstrainedContinuousIdentitySystem,
       LinearContinuousSystem,
       AffineContinuousSystem,
       LinearControlContinuousSystem
        ....
```

In applications one just picks the system type needed (in another package we've defined internal shortnames eg. `const LCCS = LinearControlContinuousSystem` and so on). 

So, should we consider `MathematicalSystem`  to not export all systems names? Perhaps exporting a minimum number of methods (`statedim`, `stateset`, ...) and interfaces (`InitialValueProblem`), or not.

**Comment by schillic** [comment]
I do not have an opinion here.

**Comment by blegat** [comment]
Yes, we could remove exports of systems.
If we want constructing systems to be user friendly we could add macros like
```julia
@system x' = Ax, x in X
```

**Comment by mforets** [comment]
> What is the advantage of not exporting it ? Avoiding name clash ?

`MathematicalSystem` exports ~30 names; but in applications one needs a few of them only, my feel with using REPL+tab completion is that this introduces too much noise. 

> we could add macros like `@system x' = Ax, x in X`

Sounds cool, this is more or less what i had in mind in https://github.com/JuliaReach/MathematicalSystems.jl/issues/6 . I'm looking forward to support this in MathematicalSystems.

**Comment by mforets** [comment]
There is also the problem of name clash; in `LazySets`, `LinearMap` means the lazy linear map of a convex set, and in `MathematicalSystem` it is now the linear map function. 

```julia
julia> using Reachability
[ Info: Precompiling Reachability [774a0091-654f-5c65-bbdc-ad5b67b45832]
WARNING: Method definition setrounding(Type{T<:Union{Float32, Float64}}, Base.Rounding.RoundingMode{T} where T) where {T<:Union{Float32, Float64}} in module
 Base at deprecated.jl:1699 overwritten in module SetRounding at /Users/forets/.julia/packages/SetRounding/MjtxK/src/SetRounding.jl:47.
WARNING: both MathematicalSystems and LazySets export "LinearMap"; uses of it in module ReachSets must be qualified
ERROR: LoadError: LoadError: LoadError: UndefVarError: LinearMap not defined
Stacktrace:
 [1] top-level scope at none:0

 [2] include at ./boot.jl:317 [inlined]
```

Though this can be fixed with the one-liner `import LazySets.LinearMap` in the correct places (see ).

**Comment by blegat** [comment]
Yes, removing names clashes is a good argument. I prefer unexported short and simple names that names that are complicated to avoid name clash and are exported

**Comment by mforets** [comment]
> If we want constructing systems to be user friendly we could add macros like

`@system x' = Ax, x in X`

Do you know some existing Julia code or package that facilitates such kind of constructs? Starting from scratch sounds challenging. .

**Comment by schillic** [comment]
Something a bit in that direction can be found [here](https://github.com/JuliaAlgebra/SemialgebraicSets.jl/blob/master/src/macro.jl#L88) (see the README for an example).

**Comment by mforets** [comment]
The more i think about this, the less i like my initial motivation. Since one can live with either `using X` or `import X` when appropriate, and `import X; X.[TAB]` works in the REPL, there is no penalty in method discovery and the `exports` defined in `X` give a notion of "external interface" of the package.

Please reopen if you disagree 😄

**Comment by blegat** [comment]
I agree to close this, this is consistent we the decision we just made for JuMP
