### ISSUE TITLE
MathematicalSets.jl

### ISSUE THREAD

**Issue by blegat** [JuliaReach/MathematicalSystems.jl#41]
What would you think of create a `MathematicalSets.jl` package which would be similar to this one.
It would defined an `AbstractSet` (unexported to not clash with `Base.AbstractSet`) and a few common functions such as

* `space_dimension` and `dimension` : a line in a planar space have dimension 1 and space-dimension 2.
* `volume(set)`: returns the volume of a set
* `surface(set)`: returns the surface
* `A * set` : The image of all points of the set by `A`
* `A' \ set` or `set / A` : the pre-image of all the points by `A`
* `polar(set)` returns the polar
* `space_variables` : a container of size `space_dimension` with an id for each dimension (by default, it is `Base.OneTo(space_dimension(set))` but it might also be symbolic variables.
* `project(set::AbstractSet, variables)` project onto `variables` which is a subset of `space_variables(set)`
* `eliminate(set::AbstractSet, variables)` same as `project(set, setminus(space_variables(set), variables))`.

But we could also define `AbstractCone <: AbstractSet` and then

* `dual(::AbstractCone)` returns the dual

And also `AbstractSymmetricSet <: AbstractSet` for sets that are symmetric around the origin.

We could also define recipes for plotting (it would add [`RecipesBase`](https://github.com/JuliaPlots/RecipesBase.jl) as a dependency).

Then we could define
```julia
struct SymmetricHyperCube{T} <: AbstractSymmetricSet
    space_dimension::Int
    half_side::T
end
struct SymmetricHyperRectangle{T} <: AbstractSymmetricSet
    half_sides::Vector{T}
end
struct SymmetricEllipsoid{T} <: AbstractSymmetricSet
    Q::Symmetric{T, Matrix{T}}
end
```
and so on...

I see several packages that would defined their sets as `AbstractSet`: https://github.com/JuliaReach/LazySets.jl, https://github.com/blegat/SetProg.jl, https://github.com/JuliaPolyhedra/Polyhedra.jl and https://github.com/JuliaAlgebra/SemialgebraicSets.jl.

In `MathematicalSystems`, we could require that the sets are subtypes of `AbstractSet` and we could make use of `space_dimension` to check if the dimension correspond to the matrices dimensions.

What do you think ?

**Comment by schillic** [comment]
I generally like this idea of unifying different set implementations.
But I see a problem if we couple the two packages (`MathematicalSystems` and `MathematicalSets`) too tightly. This will require users of `MathematicalSystems` to use types that implement `MathematicalSets`. If they use their own custom set representation, this may scare them off. In particular, how would you know that you only need to implement `space_dimension` to work with `MathematicalSystems` (at least at this point)?

**Comment by mforets** [comment]
Sounds good.

I like to have a notion of set dimension in `MathematicalSystems` types. 

Adding interfaces in `MathematicalSets` is less clear to me since there are existing ones in `LazySets`, see [set interfaces](https://juliareach.github.io/LazySets.jl/latest/lib/interfaces.html#Set-Interfaces-1). This is not to say that i'm against `AbstractSymmetricSet <: AbstractSet` but we should be careful to make things coherent. 

(On a more or less related note, an open issue in `LazySets` is how to introduce non-convex set representations to the toolbox (LazySets are assumed to be convex throughout, but there are simple use cases such as set union that are non-convex). Perhaps `MathematicalSets` can be helpful providing such an abstract type for convex / non-convex. We also thought about a trait system but we haven't implemented it.)

**Comment by mforets** [comment]
> how would you know that you only need to implement space_dimension to work with MathematicalSystems (at least at this point)?

I was checking -- sets are used in this repo as struct fields for systems with a state constraint, or as parameters for inputs (subtypes of `AbstractInput`). In either case one would add a constraint of the form `ST<:AbstractSet` in the given type parameter. It seems to me that for this package only the ambient dimension is needed to add a new check in the constructor.

**Comment by schillic** [comment]
I did not want to sound too pessimistic. As long as we clearly write that we only need this one function, it should be possible for most users to make their set types inherit from `AbstractSet`.
The only real problem I see is that there is no notion of interfaces in Julia. You would use abstract types for that, but you can only inherit from one abstract type at a time. So in some use cases you may not be able to inherit from `AbstractSet`.

**Comment by blegat** [comment]
> So in some use cases you may not be able to inherit from `AbstractSet`.

Maybe in this case, it means that the supertype is also an `AbstractSet` and he could inherit from `AbstractSet`, and recusively until you reach the abstract type which have no super type and you can make it inherit from `AbstractSet` ?
We could add an unexported
```julia
struct Set{S}
    space_dimension::Int
    set::S
end
space_dimension(s::Set) = s.space_dimension
```
in which a set that is not an `AbstractSet` can be wrapped.

**Comment by schillic** [comment]
Then the only remaining question is: In which (Github) organization do we create the package? :thinking:

**Comment by blegat** [comment]
JuliaMath might be the most appropriate but we can start creating it in JuliaReach so that it is in the same organization than `MathematicalSystems.jl` and see if we move it afterward.

**Comment by mforets** [comment]
See [JuliaReach/MathematicalSets.jl](https://github.com/JuliaReach/MathematicalSets.jl).
