### ISSUE TITLE
Create systems using UniformScaling

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#44]
See [this comment](https://github.com/JuliaReach/MathematicalSystems.jl/issues/40#issuecomment-446040193).

**Comment by schillic** [comment]
Regarding [this comment](https://github.com/JuliaReach/MathematicalSystems.jl/pull/43#issuecomment-446210073):
> For #44 one way would be to transform (in a new constructor) the UniformScaling to a sparse matrix.

I see the following options.:
1. Do what you proposed.
2. Use a type parameter that includes `UniformScaling` (via a `Union`).
3. Add a new wrapper type, e.g.,
```julia
struct US{N} < AbstractMatrix{N} where N
    M::UniformScaling{N}
end
```
and implement all methods from the `AbstractMatrix` interface.

**Comment by blegat** [comment]
I'd rather have 3. The only thing missing from a `UniformScaling` to be a matrix is a size so
```julia
struct US{N} < AbstractMatrix{N} where N
    M::UniformScaling{N}
    n::Int
end
```
should work
