### ISSUE TITLE
Parse systems expressions

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#6]
An expression like `:(x' = A*x)`, could be automatically interpreted as the more verbose `LinearContinuousSystem(A)`. Think of `:(x' = A*x + u)` or more complicated right-hand sides -- it would simplify the definition of systems.

**Comment by schillic** [comment]
But for discrete systems the definition is "more complicated".
Maybe a mixture `CS(:(A*x))` and `DS(:(A*x))`?

It is also not clear to me if `A` can really be a matrix, which is important to create the system. Also, for `u`, how do you pass the domain constraints?

**Comment by mforets** [comment]
I think it should take the shape of a domain specific language (DSL), cf. [SciCompDSL](https://github.com/JuliaDiffEq/SciCompDSL.jl ).

**Comment by mforets** [comment]
Superseded by https://github.com/JuliaReach/MathematicalSystems.jl/issues/76.
