### ISSUE TITLE
Add @system macro

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#76]
Initially i thought about: `@system x -> A*x` to define a `LinearContinuousSystem`. This is saying two things:`@system` defines a continuous ODE, and the anonymous function `x -> f(x, u)` refers to the right-hand side map of the ODE.

Alternatively let `@continous_system x -> A*x` and `@discrete_system x-> A*x` but it is kind of verbose and it's what we wanted to avoid with the macros.. or `@cont_sys` and `@cont_sys`..

Or a specific convention could be used for discrete systems, such as `@system x_k -> A*x_k`.

**Comment by blegat** [comment]
The `->` is maybe more appropriate for maps, why not doing
```julia
@system x' = Ax
```
for continuous systems and
```julia
@system x+ = Ax
```
for discrete ones ?

**Comment by mforets** [comment]
The downside is perhaps that if there are inputs, there is one less symbol to match. Compare:

```julia
@system x' = A*x + B*u  # what is the matching pattern for B*u?  _B * _u ?

@system (x, u) -> A*x + B*u # the matching pattern is _A*x + _B*u 
```

I still find that `x' = A*x + B*u` comes more natural to define ODEs, and i like the `x+ = ...` convention for the discrete case.

**Comment by schillic** [comment]
Or maybe just `@systemc` and `@systemd`?

**Comment by mforets** [comment]
CCing @ueliwechsler in case you would like to chime in.

> Or maybe just @systemc and @systemd (resp. @csystem and @dsystem)?

I like to have as little number of macros as possible, so i prefer to let the nature of the system be determined by syntax, as in `x' = ...` for continuous systems and `x+ = ...` for discrete ones.

**Comment by ueliwechsler** [comment]
I really like the syntax with `@system`, i.e. the proposed syntax
> ```julia
> @system x' = Ax
> ```
> ```julia
> @system x+ = Ax
> ```
It is nice and clean and not ambiguous. 

The only extension I can think of  is to add the option to allow to also use a superscript plus `⁺`  e.g.  ` @system x⁺ = Ax` 😅

But, how would you define the `ConstrainedSystems, something like this?
```julia
 @system x⁺ =  Ax + Bu + Dw, x ∈ X, u ∈ U, w ∈ W
```
```julia
 @system x⁺ =  Ax + Bu + Dw, (x,u,w) ∈ (X, U, W)
```
And I am just wondering if it  would be also possible to define the system like this?
```julia
A_new = rand(2,2)
 @system x⁺ =  A_new x 
```
I.e, not using the exact symbol for the variable matrix entries or having a space in between the symbols.

**Comment by mforets** [comment]
> The only extension I can think of is to add the option to allow to also use a superscript plus ⁺ 

Sounds good.

> But, how would you define the `ConstrainedSystems, something like this?

Yes, the first option using the membership symbol is what i had in mind, separing the different constraints by commas (or by an empty space? or both?).

> I.e, not using the exact symbol for the variable matrix entries or having a space in between the symbols.

Yes, the symbols should not be restricted to "x", or "A"; the macro should work with other symbols too. About the space or not, i don't know. It is nice to have `x' = Ax`  be parsed correctly, although `x' = A*x` seems easier to handle as one can search for the `*` operand...

**Comment by ueliwechsler** [comment]
I have written a first draft of the `@system` macro. 
It enables you to write ` @system( x⁺ =  Ax + Bu + Dw, x ∈ X, u ∈ U, w ∈ W)`
 or with `*` ` @system( x⁺ =  A*x + B*u + D*w, x ∈ X, u ∈ U, w ∈ W)`
or a mixture of both ` @system( x⁺ =  Ax + B*u + Dw, x ∈ X, u ∈ U, w ∈ W)`

The variables `x⁺`,`x`, `u` and `w` are required (depending on the type you want to create) but the arrays 
`A`, `B`,  `c` and `D` as well as `X`, `U` and `W` can be any variable that is defined previously.

Similarly, for a `BlackBoxSystem`,  ` @system( x⁺ =  f(x,u,w) x ∈ X, u ∈ U, w ∈ W)`
works, where `f`, `x` , `u` and `w` can be any variable, but required to be defined previoulsy.

**Comment by mforets** [comment]
Sounds really cool :100:  Here is a draft with the desired behavior: https://gist.github.com/mforets/b808e12f6ac48a079b6c5915dc98c0ea

There are also some open ends, subject to consideration.

**Comment by ueliwechsler** [comment]
@mforets and I  have invested quite some work in making the `@system` come alive.

See https://github.com/JuliaReach/MathematicalSystems.jl/tree/76, especially
https://github.com/JuliaReach/MathematicalSystems.jl/blob/14d3f014d6bfb9142045d90784260cfe80bfc601/src/macros.jl#L95-L396 
for more information (on the running, but not optimized, beautified and documented code)

See 
https://github.com/JuliaReach/MathematicalSystems.jl/blob/14d3f014d6bfb9142045d90784260cfe80bfc601/test/%40system.jl#L1-L163
 for how we intend the macro to work.

**Comment by mforets** [comment]
Well, thanks a lot for pushing forward the PR :+1:  I just gave a couple of suggestions on the API and some suggestions on `parse_system`, but you did the hard work :laughing: 

I saw that you made two test files, `@system.jl` and `@system_utilities.jl`. What was the purpose? Shall we merge them into a single file?

There are other review comments that i have in mind, but would you mind making a PR? We can mark it as WIP: ... for the time being.

**Comment by ueliwechsler** [comment]
> What was the purpose? Shall we merge them into a single file?

Yes sure. I mainly wanted to remind myself to also create tests for the helper methods.
