### ISSUE TITLE
Add missing arithmetic operations of IdentityMultiple

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#90]

**Comment by schillic** [comment]
Since this will be supported in Julia v1.2 anyway, I would not invest too much time here.

**Comment by mforets** [comment]
Good point, we should discuss if we want to drop `IdentityMultiple` altogether or not.

The drawback is that`I(2)` will not be special type; it's just a shortcut for the creation of a  `Diagonal` matrix as far as i can tell (see [here](https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/uniformscaling.jl#L74)).

**Comment by ueliwechsler** [comment]
A short unrelated thought on `IdentityMultiple` from my side.

Dealing with identity matrices, i.e. `UniformScaling`, was one of the things that did really bother me in `julia` ( because compared to `matlab` where you could just call `eye` it felt so verbose). But now that I know about the entire scope of `IdentityMultiple`,  I am so excited about the `IdentityMultiple`. It so easy to create with `I(n)` and is also of subtype `AbstractArray`,  I love it 😍.
This should definitely be a `Base`, i.e. `LinearAlgebra` feature.

**Comment by ueliwechsler** [comment]
And also some technical thought:
- Should we allow `2/I(1)` to return `2`? i.e.  allow division of a scalar by a ìdentity multiple with order 1. 
- Should we add more informative error messages in general for `2/I(2)`, i.e. an error talking about the dimension mismatch instead of a method error?

**Comment by schillic** [comment]
> * Should we allow `2/I(1)` to return `2`? i.e.  allow division of a scalar by a ìdentity multiple with order 1.

I am not sure why this should be supported. Dividing a scalar by a matrix is not supported in Julia.

```julia
julia> 1.0 / ones(1, 1)
ERROR: MethodError: no method matching /(::Float64, ::Array{Float64,2})
```

Do you have a use case?

On a separate note, I first thought that `2/I(1)` should return an `IdentityMultiple` again:

```julia
function (/)(a::T, im::IdentityMultiple{T} where {T}
    return I(a * im.M, im.n)
end
```

But that is not a good idea because `/` should be the inverse operation of `*`. 

> * Should we add more informative error messages in general for `2/I(2)`, i.e. an error talking about the dimension mismatch instead of a method error?

If the above were implemented: yes.

**Comment by ueliwechsler** [comment]
Thanks for the elaboration.

> Do you have a use case?

No, I was just wondering if there are argument operator combinations that are not implemented yet.

**Comment by mforets** [comment]
> This should definitely be a Base, i.e. LinearAlgebra feature.

Note that since Julia v1.2, `UniformScaling` [instances are callable](https://docs.julialang.org/en/v1.2/NEWS/#LinearAlgebra-1), hence for example `1.0I(2)` produces a 2x2 `Diagonal` matrix with floating point entries (FWIW, we wrote the `IdentityMultple` in previous versions of Julia, so it was more justified). In practice, using `UniformScaling` should be fine; i doubt there are applications where `IdentityMultple` is much better than diagonal matrices. In any case, this type should probably be outsourced to its own little package.

> I am not sure why this should be supported. Dividing a scalar by a matrix is not supported in Julia.

I agree. But the inverse operation should still be added:

```julia
julia> UniformScaling(2)
UniformScaling{Int64}
2*I

julia> inv(UniformScaling(2))
UniformScaling{Float64}
0.5*I

julia> I(2)
IdentityMultiple{Float64} of value 1.0 and order 2

julia> inv(I(2))
ERROR: MethodError: no method matching factorize(::IdentityMultiple{Float64})
Closest candidates are:
  factorize(::Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where T at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/dense.jl:1157
  factorize(::Adjoint) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/dense.jl:1232
  factorize(::Transpose) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/dense.jl:1233
  ...
Stacktrace:
 [1] inv(::IdentityMultiple{Float64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/generic.jl:901
 [2] top-level scope at REPL[27]:1

```
