### ISSUE TITLE
Add function to return the successor in a discrete system

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#96]
`successor(system::ConstrainedLinearControlDiscreteSystem, x, u)` would return the result of `system.A*x + system.B*u` and so on.

**Comment by ueliwechsler** [comment]
Would it be reasonable to also add state and input dimension and constraint checks, e.g. such as:
```julia
function successor(system::ConstrainedLinearControlDiscreteSystem, x, u)
    @assert statedim(system) == length(x) && inputdim(system) == length(u)
    @assert x ∈ system.X && u ∈ system.U
    return system.A*x + system.B*u
end
```

**Comment by mforets** [comment]
Yes, it is reasonable to add such kind of checks. In that case, i would annotate the type of `x` and `u` as well, asking that they are (abstract) vectors. That's because it is also ok to let `x` and `u` be other objects, such as *sets* themselves, in which case it makes sense to check that `statedim(system) == dim(x)` and similarly for `u`, but it doesn't make sense to ask for the `length` of a set. This use case appears naturally in reachability, since a continuous ODE is discretized into a set-based recurrence.

We want this library to be as light-weight as possible. In particular, it does not depend on LazySets. On the long run, i'd like to use [MathematicalSets](https://github.com/JuliaReach/MathematicalSets.jl) such that we let `x` to be an `AbstractSet` and the check dimensional check is natural for sets too (LazySets would subtype an AbstractSet).

**Comment by schillic** [comment]
The same implementation for continuous systems can also be useful. But the name `successor` does not make sense there (`derivative` or `tangent` would be more appropriate). I suggest to offer the same functionality for continuous systems and use a common name for code sharing. We can still have `successor` as an alias for convenience.
Possible names: `substitute`, `apply`, `instantiate`

**Comment by mforets** [comment]
True, for cont systems that's the [vector field](https://en.wikipedia.org/wiki/Vector_field) corresponding to the [slope field](https://en.wikipedia.org/wiki/Slope_field) of the ODE.

> We can still have successor as an alias for convenience.

:-1:
