### ISSUE TITLE
Add NoisyXYZsystem 

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/MathematicalSystems.jl#97]
I would like to add noisy mathematical systems, i.e. a system with additive bounded noise such as `x+ = Ax + Bu + c + Dw`, for the application in robust control.
As an example, I have a version of a `NoisyConstrainedAffineControlDiscreteSystem`. 
First of all, do you agree to include these types? And if so, which system types would need to be extended? For my use-case I am mostly in need of linear and affine ControlDiscreteSystems, however, I assume this should be done for more types.

```julia
using MathematicalSystems

for (Z, AZ) in ((:NoisyConstrainedAffineControlContinuousSystem, :AbstractContinuousSystem),
                (:NoisyConstrainedAffineControlDiscreteSystem, :AbstractDiscreteSystem))
    @eval begin
        struct $(Z){T, MTA <: AbstractMatrix{T}, MTB <: AbstractMatrix{T}, MTD <: AbstractMatrix{T}, VT <: AbstractVector{T}, ST, UT, WT} <: $(AZ)
            A::MTA
            B::MTB
            c::VT
            D::MTD
            X::ST
            U::UT
            W::WT
            function $(Z)(A::MTA, B::MTB, c::VT, X::ST, U::UT) where {T, MTA <: AbstractMatrix{T}, MTB <: AbstractMatrix{T}, VT <: AbstractVector{T}, ST, UT}
                @assert checksquare(A) == length(c) == size(B, 1) == size(W,1)
                return new{T, MTA, MTB, VT, MTD, ST, UT, WT}(A, B, c, D, X, U, W)
            end
        end
        statedim(s::$Z) = length(s.c)
        stateset(s::$Z) = s.X
        inputdim(s::$Z) = size(s.B, 2)
        inputset(s::$Z) = s.U
        noisedim(s::$Z) = size(s.D, 2)
        noiseset(s::$Z) = s.W
        islinear(::$Z) = false
        isaffine(::$Z) = true
        isnoisy(::$Z) = true
    end
end

**Comment by mforets** [comment]
Thanks for bringing this idea and taking the time to draft the new type in question.

> First of all, do you agree to include these types?

I think that it is nice to add the proposed type. Control literature refers to such `w` as the *unknown disturbance* or the *noise*, so it's fair to add a type for this standard use case.

> And if so, which system types would need to be extended?

Even though the noise can in principle be added to all system's types that sounds like a lot of work :fearful: Unless we use tooling to extend a given type by adding more fields (i remember to have seen such tools, but i forgot the name). In any case, i don't suggest to spend time in that. Adding the new types `NoisyConstrainedAffineControlDiscreteSystem` / `NoisyConstrainedLinearControlDiscreteSystem` as you've proposed above sounds fine. Feel free to open a PR.

**Comment by ueliwechsler** [comment]
I was considering tooling, but in the end I just hardcoded most of it.

Once #96 is merged, I will extend the `successor` method for the `NoisySystems`.

I was thining about to possible options.
```julia
successor(sys, x, u, w)
```
and 
```julia
using LazySets, Distributions
successor(sys,x,u) = successor(sys, x, u, sys.D *sample(sys.𝒲))
```
Note: In order to efficiently apply the successor multiple times, I'd like to implement a `sample` method not only for a `LazySet` but also for a `LazySets.Sampler` e.g.
```julia
using LazySets, Distributions
noise = LazySets.RejectionSampler(𝒲)
successor(sys, x, u, sample(noise))
```
since `sample(𝒲)` creates a new `RejectionSampler` every time it is applied.
